apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "hello-kubernetes.fullname" . } }
  labels: { { - include "hello-kubernetes.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      { { - include "hello-kubernetes.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "hello-kubernetes.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { include "hello-kubernetes.name" . } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: 80
